export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const OBTENER_POSTS = 'OBTENER_POSTS';
export const AGREGAR_POST = 'AGREGAR_POST';
export const POST_SELECCIONADO = 'POST_SELECCIONADO';
export const ELIMINAR_POST = 'ELIMINAR_POST';
export const ACTUALIZAR_POST = 'ACTUALIZAR_POST';
export const LIMPIAR_POST = 'LIMPIAR_POST';
export const LIMPIAR_POSTS = 'LIMPIAR_POSTS';
